
[[constraint]]
  name = "github.com/coreos/go-oidc"
  version = "2.0.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.14.1"

[[constraint]]
  name = "github.com/google/uuid"
  version = "1.0.0"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.4.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[prune]
  go-tests = true
  unused-packages = true
